theme = "carbonfox"

[editor]
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 500
focus-last = true

[editor.whitespace]
render = "all"

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "file-line-ending", "file-encoding", "position"]
separator = "│"


# another workaround for auto-save on escape
# not required. but in-case the autosave fails

# [keys.normal]
# "esc" = ["collapse_selection", ":w"]

# [keys.select]
# "esc" = ["collapse_selection", "normal_mode", ":w"]

# [keys.insert]
# "esc" = ["normal_mode", ":w"]
